### ISSUE TITLE
Download and preprocess the data      Download the Precomputing ResNet Image Features, and extract them into img_features/:

### ISSUE THREAD

**Issue by michelm117** [ronghanghu/speaker_follower#15] opened 2019-02-20 16:57 UTC
Hi, 
it is no longer possible to download the R2R dataset.

```
wget https://storage.googleapis.com/bringmeaspoon/img_features/ResNet-152-imagenet.zip -O ResNet-152-imagenet.zip
--2019-02-20 17:51:23--  https://storage.googleapis.com/bringmeaspoon/img_features/ResNet-152-imagenet.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.205.240, 2a00:1450:4001:820::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.205.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-20 17:51:24 ERROR 403: Forbidden.
```
and

```
./tasks/R2R/data/download.sh
--2019-02-20 17:56:43--  https://storage.googleapis.com/bringmeaspoon/R2Rdata/R2R_train.json
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.205.240, 2a00:1450:4001:820::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.205.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-20 17:56:43 ERROR 403: Forbidden.

--2019-02-20 17:56:43--  https://storage.googleapis.com/bringmeaspoon/R2Rdata/R2R_val_seen.json
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.205.240, 2a00:1450:4001:820::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.205.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-20 17:56:43 ERROR 403: Forbidden.

--2019-02-20 17:56:43--  https://storage.googleapis.com/bringmeaspoon/R2Rdata/R2R_val_unseen.json
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.205.240, 2a00:1450:4001:820::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.205.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-20 17:56:44 ERROR 403: Forbidden.

--2019-02-20 17:56:44--  https://storage.googleapis.com/bringmeaspoon/R2Rdata/R2R_test.json
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.205.240, 2a00:1450:4001:820::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.205.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-20 17:56:44 ERROR 403: Forbidden.
```

**Comment by ronghanghu** [comment] 2019-02-20 17:12
Hmm, it seems that the download link for `ResNet-152-imagenet features [380K/2.9GB]` from the R2R dataset repo (https://github.com/peteanderson80/Matterport3DSimulator) has expired.

As an alternative, it is possible to extract those features using the provided scripts in https://github.com/peteanderson80/Matterport3DSimulator/tree/master/scripts

**Comment by YicongHong** [comment] 2019-02-24 22:13
the problem is now fixed, see:
https://github.com/peteanderson80/Matterport3DSimulator/commit/31e7e3ed5927d38e03a71444073bcbbc98c462d8

**Comment by ronghanghu** [comment] 2019-02-24 22:37
Thanks! I've just updated the links in this repo to match peteanderson80/Matterport3DSimulator@31e7e3e

**Closed by ronghanghu** 2019-02-24 22:37 UTC
